### ISSUE TITLE
Drone is Deprecated

### ISSUE THREAD

**Issue by Serob** [takanorig/mqtt-bench#11]
For downloading binaries there's a _Deprecation Warning_ on Drone site and it seems that there is not any file to download.

**Comment by briantully** [comment]
same. any way to download the Mac OSX binary?

alternatively I cannot install via go either. keeps asking for password :(

**Comment by Serob** [comment]
I found this. Maybe it can help you ))
https://github.com/takanorig/mqtt-bench/releases

**Comment by briantully** [comment]
Thank you @Serob ! :D 👍
